name: screentranslator
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_overlay_window: ^0.4.5
  permission_handler: ^11.4.0
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.15.0
  screenshot: ^3.0.0
  flutter_tesseract_ocr: ^0.4.28
  translator: ^1.0.3+1
  flutter_tts: ^4.2.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/tessdata/eng.traineddata
    - assets/tessdata/tha.traineddata
    - assets/tessdata/Thai.traineddata
    - assets/tessdata/afr.traineddata
    - assets/tessdata/amh.traineddata
    - assets/tessdata/ara.traineddata
    - assets/tessdata/Arabic.traineddata
    - assets/tessdata/Armenian.traineddata
    - assets/tessdata/asm.traineddata
    - assets/tessdata/aze_cyrl.traineddata
    - assets/tessdata/bel.traineddata
    - assets/tessdata/ben.traineddata
    - assets/tessdata/Bengali.traineddata
    - assets/tessdata/bod.traineddata
    - assets/tessdata/bos.traineddata
    - assets/tessdata/bre.traineddata
    - assets/tessdata/bul.traineddata
    - assets/tessdata/Canadian_Aboriginal.traineddata
    - assets/tessdata/cat.traineddata
    - assets/tessdata/ceb.traineddata
    - assets/tessdata/ces.traineddata
    - assets/tessdata/Cherokee.traineddata
    - assets/tessdata/chi_sim_vert.traineddata
    - assets/tessdata/chi_sim.traineddata
    - assets/tessdata/chi_tra_vert.traineddata
    - assets/tessdata/chi_tra.traineddata
    - assets/tessdata/chr.traineddata
    - assets/tessdata/cos.traineddata
    - assets/tessdata/cym.traineddata
    - assets/tessdata/Cyrillic.traineddata
    - assets/tessdata/dan_frak.traineddata
    - assets/tessdata/dan.traineddata
    - assets/tessdata/deu_frak.traineddata
    - assets/tessdata/deu_latf.traineddata
    - assets/tessdata/deu.traineddata
    - assets/tessdata/Devanagari.traineddata
    - assets/tessdata/div.traineddata
    - assets/tessdata/dzo.traineddata
    - assets/tessdata/ell.traineddata
    - assets/tessdata/enm.traineddata
    - assets/tessdata/epo.traineddata
    - assets/tessdata/equ.traineddata
    - assets/tessdata/est.traineddata
    - assets/tessdata/Ethiopic.traineddata
    - assets/tessdata/eus.traineddata
    - assets/tessdata/fao.traineddata
    - assets/tessdata/fas.traineddata
    - assets/tessdata/fil.traineddata
    - assets/tessdata/fin.traineddata
    - assets/tessdata/fra.traineddata
    - assets/tessdata/Fraktur.traineddata
    - assets/tessdata/frm.traineddata
    - assets/tessdata/fry.traineddata
    - assets/tessdata/Georgian.traineddata
    - assets/tessdata/gla.traineddata
    - assets/tessdata/gle.traineddata
    - assets/tessdata/glg.traineddata
    - assets/tessdata/grc.traineddata
    - assets/tessdata/Greek.traineddata
    - assets/tessdata/guj.traineddata
    - assets/tessdata/Gujarati.traineddata
    - assets/tessdata/Gurmukhi.traineddata
    - assets/tessdata/Hangul_vert.traineddata
    - assets/tessdata/Hangul.traineddata
    - assets/tessdata/HanS_vert.traineddata
    - assets/tessdata/HanS.traineddata
    - assets/tessdata/HanT_vert.traineddata
    - assets/tessdata/HanT.traineddata
    - assets/tessdata/hat.traineddata
    - assets/tessdata/heb.traineddata
    - assets/tessdata/Hebrew.traineddata
    - assets/tessdata/hin.traineddata
    - assets/tessdata/hrv.traineddata
    - assets/tessdata/hun.traineddata
    - assets/tessdata/hye.traineddata
    - assets/tessdata/iku.traineddata
    - assets/tessdata/ind.traineddata
    - assets/tessdata/isl.traineddata
    - assets/tessdata/ita_old.traineddata
    - assets/tessdata/ita.traineddata
    - assets/tessdata/Japanese_vert.traineddata
    - assets/tessdata/Japanese.traineddata
    - assets/tessdata/jav.traineddata
    - assets/tessdata/jpn_vert.traineddata
    - assets/tessdata/jpn.traineddata
    - assets/tessdata/kan.traineddata
    - assets/tessdata/Kannada.traineddata
    - assets/tessdata/kat_old.traineddata
    - assets/tessdata/kat.traineddata
    - assets/tessdata/kaz.traineddata
    - assets/tessdata/Khmer.traineddata
    - assets/tessdata/kir.traineddata
    - assets/tessdata/kmr.traineddata
    - assets/tessdata/kor_vert.traineddata
    - assets/tessdata/kor.traineddata
    - assets/tessdata/Lao.traineddata
    - assets/tessdata/lat.traineddata
    - assets/tessdata/Latin.traineddata
    - assets/tessdata/lav.traineddata
    - assets/tessdata/lit.traineddata
    - assets/tessdata/ltz.traineddata
    - assets/tessdata/Malayalam.traineddata
    - assets/tessdata/mar.traineddata
    - assets/tessdata/mkd.traineddata
    - assets/tessdata/mlt.traineddata
    - assets/tessdata/mon.traineddata
    - assets/tessdata/mri.traineddata
    - assets/tessdata/msa.traineddata
    - assets/tessdata/mya.traineddata
    - assets/tessdata/Myanmar.traineddata
    - assets/tessdata/nep.traineddata
    - assets/tessdata/nld.traineddata
    - assets/tessdata/nor.traineddata
    - assets/tessdata/oci.traineddata
    - assets/tessdata/ori.traineddata
    - assets/tessdata/osd.traineddata
    - assets/tessdata/pan.traineddata
    - assets/tessdata/pol.traineddata
    - assets/tessdata/por.traineddata
    - assets/tessdata/pus.traineddata
    - assets/tessdata/que.traineddata
    - assets/tessdata/ron.traineddata
    - assets/tessdata/rus.traineddata
    - assets/tessdata/san.traineddata
    - assets/tessdata/sin.traineddata
    - assets/tessdata/Sinhala.traineddata
    - assets/tessdata/slk_frak.traineddata
    - assets/tessdata/slk.traineddata
    - assets/tessdata/slv.traineddata
    - assets/tessdata/snd.traineddata
    - assets/tessdata/spa_old.traineddata
    - assets/tessdata/spa.traineddata
    - assets/tessdata/sqi.traineddata
    - assets/tessdata/srp_latn.traineddata
    - assets/tessdata/srp.traineddata
    - assets/tessdata/sun.traineddata
    - assets/tessdata/swa.traineddata
    - assets/tessdata/swe.traineddata
    - assets/tessdata/syr.traineddata
    - assets/tessdata/Syriac.traineddata
    - assets/tessdata/tam.traineddata
    - assets/tessdata/Tamil.traineddata
    - assets/tessdata/tat.traineddata
    - assets/tessdata/tel.traineddata
    - assets/tessdata/Telugu.traineddata
    - assets/tessdata/tgk.traineddata
    - assets/tessdata/tgl.traineddata
    - assets/tessdata/Thaana.traineddata
    - assets/tessdata/Thai.traineddata
    - assets/tessdata/Tibetan.traineddata
    - assets/tessdata/tir.traineddata
    - assets/tessdata/ton.traineddata
    - assets/tessdata/tur.traineddata
    - assets/tessdata/uig.traineddata
    - assets/tessdata/ukr.traineddata
    - assets/tessdata/urd.traineddata
    - assets/tessdata/uzb_cyrl.traineddata
    - assets/tessdata/uzb.traineddata
    - assets/tessdata/vie.traineddata
    - assets/tessdata/Vietnamese.traineddata
    - assets/tessdata/yid.traineddata
    - assets/tessdata_config.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
